export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={children}>
        {children} {/* Renderize o conteúdo do children aqui */}
      </body>
    </html>
  )
}